# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.api.youtube_api import YoutubeApi  # noqa: E501


class TestYoutubeApi(unittest.TestCase):
    """YoutubeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = YoutubeApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_search_you_tube(self) -> None:
        """Test case for search_you_tube

        Search Youtube  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
