# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sharedapi_client.models.cash_app_profile import CashAppProfile  # noqa: E501

class TestCashAppProfile(unittest.TestCase):
    """CashAppProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashAppProfile:
        """Test CashAppProfile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashAppProfile`
        """
        model = CashAppProfile()  # noqa: E501
        if include_optional:
            return CashAppProfile(
                display_name = None,
                formatted_cashtag = None,
                is_verified_account = None,
                rate_plan = None,
                payment_button_type = None,
                country_code = None,
                avatar = sharedapi_client.models.avatar.Avatar(
                    image_url = null, 
                    initial = null, 
                    accent_color = null, )
            )
        else:
            return CashAppProfile(
        )
        """

    def testCashAppProfile(self):
        """Test CashAppProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
