# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sharedapi_client.models.mmr_data import MMRData  # noqa: E501

class TestMMRData(unittest.TestCase):
    """MMRData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MMRData:
        """Test MMRData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MMRData`
        """
        model = MMRData()  # noqa: E501
        if include_optional:
            return MMRData(
                name = None,
                tag = None,
                current_data = sharedapi_client.models.current_data.CurrentData(
                    currenttier = null, 
                    currenttierpatched = null, 
                    images = sharedapi_client.models.datum_images.DatumImages(
                        small = null, 
                        large = null, 
                        triangle_down = null, 
                        triangle_up = null, ), 
                    ranking_in_tier = null, 
                    mmr_change_to_last_game = null, 
                    elo = null, 
                    games_needed_for_rating = null, 
                    old = null, ),
                highest_rank = sharedapi_client.models.highest_rank.HighestRank(
                    old = null, 
                    tier = null, 
                    patched_tier = null, 
                    season = null, 
                    converted = null, ),
                by_season = {
                    'key' : sharedapi_client.models.e1_a1.E1A1(
                        wins = null, 
                        number_of_games = null, 
                        final_rank = null, 
                        final_rank_patched = null, 
                        act_rank_wins = null, 
                        old = null, )
                    }
            )
        else:
            return MMRData(
        )
        """

    def testMMRData(self):
        """Test MMRData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
