# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.api.ai_api import AiApi  # noqa: E501


class TestAiApi(unittest.TestCase):
    """AiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AiApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_createartwithdalle2(self) -> None:
        """Test case for createartwithdalle2

        Create Art With Dalle-2  # noqa: E501
        """
        pass

    def test_createcyberpunkavatar(self) -> None:
        """Test case for createcyberpunkavatar

        Create Cyberpunk Avatar  # noqa: E501
        """
        pass

    def test_createfantasyartavatar(self) -> None:
        """Test case for createfantasyartavatar

        Create Fantasy Art Avatar  # noqa: E501
        """
        pass

    def test_createpixelavatar(self) -> None:
        """Test case for createpixelavatar

        Create Pixel Avatar  # noqa: E501
        """
        pass

    def test_evaluate_image_safety(self) -> None:
        """Test case for evaluate_image_safety

        Evaluate Image Safety  # noqa: E501
        """
        pass

    def test_read_textfrom_image(self) -> None:
        """Test case for read_textfrom_image

        Read Text From Image  # noqa: E501
        """
        pass

    def test_removebackgroundsfromimage(self) -> None:
        """Test case for removebackgroundsfromimage

        Remove Backgrounds From Image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
