# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sharedapi_client.models.tik_tok_video_response import TikTokVideoResponse  # noqa: E501

class TestTikTokVideoResponse(unittest.TestCase):
    """TikTokVideoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TikTokVideoResponse:
        """Test TikTokVideoResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TikTokVideoResponse`
        """
        model = TikTokVideoResponse()  # noqa: E501
        if include_optional:
            return TikTokVideoResponse(
                aweme_id = None,
                avatar_bytes = None,
                video_url = None,
                author_id = None,
                author = sharedapi_client.models.author.Author(
                    avatar_thumb = null, 
                    unique_id = null, ),
                avatar_thumb = None,
                create_time = None,
                desc = None,
                direct_download_urls = None,
                filename = None,
                id = None,
                music = sharedapi_client.models.music.Music(
                    duration = null, 
                    album = null, 
                    id = null, 
                    title = null, ),
                nickname = None,
                statistics = sharedapi_client.models.statistics.Statistics(
                    digg_count = null, 
                    play_count = null, 
                    share_count = null, 
                    comment_count = null, ),
                video_bytes = None,
                share_url = None,
                video = sharedapi_client.models.video.Video(
                    ratio = null, 
                    height = null, 
                    width = null, 
                    dynamic_cover = null, 
                    origin_cover = null, 
                    duration = null, ),
                cover_image_url = None,
                image_post_info = sharedapi_client.models.image_post_info.ImagePostInfo(
                    images = null, ),
                embed_color = None
            )
        else:
            return TikTokVideoResponse(
        )
        """

    def testTikTokVideoResponse(self):
        """Test TikTokVideoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
