# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.ai_image_generation_response import AIImageGenerationResponse  # noqa: E501


class TestAIImageGenerationResponse(unittest.TestCase):
    """AIImageGenerationResponse unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIImageGenerationResponse:
        """Test AIImageGenerationResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `AIImageGenerationResponse`
        """
        model = AIImageGenerationResponse()  # noqa: E501
        if include_optional:
            return AIImageGenerationResponse(
                url = None,
                idea = None
            )
        else:
            return AIImageGenerationResponse(
                url = None,
                idea = None,
        )
        """

    def testAIImageGenerationResponse(self):
        """Test AIImageGenerationResponse."""


if __name__ == "__main__":
    unittest.main()
