# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.melanie_models_sharedapi_twitter_user_tweets_url_class import MelanieModelsSharedapiTwitterUserTweetsURLClass  # noqa: E501


class TestMelanieModelsSharedapiTwitterUserTweetsURLClass(unittest.TestCase):
    """MelanieModelsSharedapiTwitterUserTweetsURLClass unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MelanieModelsSharedapiTwitterUserTweetsURLClass:
        """Test MelanieModelsSharedapiTwitterUserTweetsURLClass
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `MelanieModelsSharedapiTwitterUserTweetsURLClass`
        """
        model = MelanieModelsSharedapiTwitterUserTweetsURLClass()  # noqa: E501
        if include_optional:
            return MelanieModelsSharedapiTwitterUserTweetsURLClass(
                urls = None
            )
        else:
            return MelanieModelsSharedapiTwitterUserTweetsURLClass(
        )
        """

    def testMelanieModelsSharedapiTwitterUserTweetsURLClass(self):
        """Test MelanieModelsSharedapiTwitterUserTweetsURLClass."""


if __name__ == "__main__":
    unittest.main()
