# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.deletion_confirmation import DeletionConfirmation  # noqa: E501


class TestDeletionConfirmation(unittest.TestCase):
    """DeletionConfirmation unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeletionConfirmation:
        """Test DeletionConfirmation
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `DeletionConfirmation`
        """
        model = DeletionConfirmation()  # noqa: E501
        if include_optional:
            return DeletionConfirmation(
                confirmed = None,
                confirmed_by = None,
                deleted_items = None,
                sig = None
            )
        else:
            return DeletionConfirmation(
                confirmed = None,
                sig = None,
        )
        """

    def testDeletionConfirmation(self):
        """Test DeletionConfirmation."""


if __name__ == "__main__":
    unittest.main()
