# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.tiktok_post_request import TiktokPostRequest  # noqa: E501


class TestTiktokPostRequest(unittest.TestCase):
    """TiktokPostRequest unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TiktokPostRequest:
        """Test TiktokPostRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `TiktokPostRequest`
        """
        model = TiktokPostRequest()  # noqa: E501
        if include_optional:
            return TiktokPostRequest(
                url = None
            )
        else:
            return TiktokPostRequest(
        )
        """

    def testTiktokPostRequest(self):
        """Test TiktokPostRequest."""


if __name__ == "__main__":
    unittest.main()
