# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.api.roblox_api import RobloxApi  # noqa: E501


class TestRobloxApi(unittest.TestCase):
    """RobloxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RobloxApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_robloxuser(self) -> None:
        """Test case for get_robloxuser

        Get Roblox User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
