# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.api.snapchat_api import SnapchatApi  # noqa: E501


class TestSnapchatApi(unittest.TestCase):
    """SnapchatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SnapchatApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_snapuser(self) -> None:
        """Test case for get_snapuser

        Get Snapuser  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
