# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sharedapi_client.models.country_flag import CountryFlag  # noqa: E501

class TestCountryFlag(unittest.TestCase):
    """CountryFlag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CountryFlag:
        """Test CountryFlag
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CountryFlag`
        """
        model = CountryFlag()  # noqa: E501
        if include_optional:
            return CountryFlag(
                emoji = None,
                unicode = None
            )
        else:
            return CountryFlag(
        )
        """

    def testCountryFlag(self):
        """Test CountryFlag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
