# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.melanie_models_sharedapi_twitter_user_tweets_description_entity import (
    MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity,  # noqa: E501
)


class TestMelanieModelsSharedapiTwitterUserTweetsDescriptionEntity(unittest.TestCase):
    """MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity:
        """Test MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity`
        """
        model = MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity()  # noqa: E501
        if include_optional:
            return MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity(
                from_index = None,
                to_index = None,
                ref = sharedapi_client.models.fluffy_ref.FluffyRef(
                    url = null,
                    url_type = null, )
            )
        else:
            return MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity(
        )
        """

    def testMelanieModelsSharedapiTwitterUserTweetsDescriptionEntity(self):
        """Test MelanieModelsSharedapiTwitterUserTweetsDescriptionEntity."""


if __name__ == "__main__":
    unittest.main()
