# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.highlight_item import HighlightItem  # noqa: E501


class TestHighlightItem(unittest.TestCase):
    """HighlightItem unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HighlightItem:
        """Test HighlightItem
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `HighlightItem`
        """
        model = HighlightItem()  # noqa: E501
        if include_optional:
            return HighlightItem(
                preview_img = None,
                title = None,
                id = None
            )
        else:
            return HighlightItem(
                id = None,
        )
        """

    def testHighlightItem(self):
        """Test HighlightItem."""


if __name__ == "__main__":
    unittest.main()
