# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.roblox_user_profile_response import RobloxUserProfileResponse  # noqa: E501


class TestRobloxUserProfileResponse(unittest.TestCase):
    """RobloxUserProfileResponse unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RobloxUserProfileResponse:
        """Test RobloxUserProfileResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `RobloxUserProfileResponse`
        """
        model = RobloxUserProfileResponse()  # noqa: E501
        if include_optional:
            return RobloxUserProfileResponse(
                name = None,
                follower_count = None,
                following_count = None,
                display_name = None,
                description = None,
                presence = None,
                has_verified_badge = None,
                created = None,
                is_banned = None,
                id = None,
                last_online = None,
                last_location = None,
                avatar_url = None,
                badges = None,
                previous_names = None
            )
        else:
            return RobloxUserProfileResponse(
        )
        """

    def testRobloxUserProfileResponse(self):
        """Test RobloxUserProfileResponse."""


if __name__ == "__main__":
    unittest.main()
