# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sharedapi_client.models.instagram_post_response import InstagramPostResponse  # noqa: E501

class TestInstagramPostResponse(unittest.TestCase):
    """InstagramPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstagramPostResponse:
        """Test InstagramPostResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstagramPostResponse`
        """
        model = InstagramPostResponse()  # noqa: E501
        if include_optional:
            return InstagramPostResponse(
                num_results = None,
                share_url = None,
                author = sharedapi_client.models.instagram_user_response.InstagramUserResponse(
                    username = null, 
                    full_name = null, 
                    is_private = null, 
                    avatar_filename = null, 
                    avatar_url = null, 
                    is_verified = null, ),
                items = None
            )
        else:
            return InstagramPostResponse(
        )
        """

    def testInstagramPostResponse(self):
        """Test InstagramPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
