# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.instagram_post_request import InstagramPostRequest  # noqa: E501


class TestInstagramPostRequest(unittest.TestCase):
    """InstagramPostRequest unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstagramPostRequest:
        """Test InstagramPostRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `InstagramPostRequest`
        """
        model = InstagramPostRequest()  # noqa: E501
        if include_optional:
            return InstagramPostRequest(
                content = None,
                user_id = None,
                guild_id = None
            )
        else:
            return InstagramPostRequest(
                content = None,
                user_id = None,
                guild_id = None,
        )
        """

    def testInstagramPostRequest(self):
        """Test InstagramPostRequest."""


if __name__ == "__main__":
    unittest.main()
