# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.instagram_carousel_media_response import InstagramCarouselMediaResponse  # noqa: E501


class TestInstagramCarouselMediaResponse(unittest.TestCase):
    """InstagramCarouselMediaResponse unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstagramCarouselMediaResponse:
        """Test InstagramCarouselMediaResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `InstagramCarouselMediaResponse`
        """
        model = InstagramCarouselMediaResponse()  # noqa: E501
        if include_optional:
            return InstagramCarouselMediaResponse(
                url = None,
                preview_image_url = None,
                preview_image_filename = None,
                is_video = None,
                filename = None
            )
        else:
            return InstagramCarouselMediaResponse(
        )
        """

    def testInstagramCarouselMediaResponse(self):
        """Test InstagramCarouselMediaResponse."""


if __name__ == "__main__":
    unittest.main()
