# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sharedapi_client.models.melanie_models_sharedapi_twitter_user_tweets_reason import MelanieModelsSharedapiTwitterUserTweetsReason  # noqa: E501

class TestMelanieModelsSharedapiTwitterUserTweetsReason(unittest.TestCase):
    """MelanieModelsSharedapiTwitterUserTweetsReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MelanieModelsSharedapiTwitterUserTweetsReason:
        """Test MelanieModelsSharedapiTwitterUserTweetsReason
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MelanieModelsSharedapiTwitterUserTweetsReason`
        """
        model = MelanieModelsSharedapiTwitterUserTweetsReason()  # noqa: E501
        if include_optional:
            return MelanieModelsSharedapiTwitterUserTweetsReason(
                description = sharedapi_client.models.reason_description.ReasonDescription(
                    text = null, 
                    entities = null, ),
                verified_since_msec = None
            )
        else:
            return MelanieModelsSharedapiTwitterUserTweetsReason(
        )
        """

    def testMelanieModelsSharedapiTwitterUserTweetsReason(self):
        """Test MelanieModelsSharedapiTwitterUserTweetsReason"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
