# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.api.admin_api import AdminApi  # noqa: E501


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_deleteamediacacheobject(self) -> None:
        """Test case for deleteamediacacheobject

        Delete A Media Cache Object  # noqa: E501
        """
        pass

    def test_get_rp_cendpoint(self) -> None:
        """Test case for get_rp_cendpoint

        Get Rpc Endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
