# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.tik_tok_top_video_item import TikTokTopVideoItem  # noqa: E501


class TestTikTokTopVideoItem(unittest.TestCase):
    """TikTokTopVideoItem unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TikTokTopVideoItem:
        """Test TikTokTopVideoItem
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `TikTokTopVideoItem`
        """
        model = TikTokTopVideoItem()  # noqa: E501
        if include_optional:
            return TikTokTopVideoItem(
                title = None,
                plays = None,
                url = None,
                comments = None,
                var_date = None,
                id = None
            )
        else:
            return TikTokTopVideoItem(
                title = None,
                plays = None,
                url = None,
                comments = None,
                var_date = None,
                id = None,
        )
        """

    def testTikTokTopVideoItem(self):
        """Test TikTokTopVideoItem."""


if __name__ == "__main__":
    unittest.main()
