# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.models.banner_type import BannerType  # noqa: E501


class TestBannerType(unittest.TestCase):
    """BannerType unit test stubs."""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BannerType:
        """Test BannerType
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `BannerType`
        """
        model = BannerType()  # noqa: E501
        if include_optional:
            return BannerType(
                banner = None,
                url = None,
                color = sharedapi_client.models.color_palette.ColorPalette(
                    colors = null, ),
                guild_id = None,
                format = None,
                user_id = None
            )
        else:
            return BannerType(
        )
        """

    def testBannerType(self):
        """Test BannerType."""


if __name__ == "__main__":
    unittest.main()
