# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from sharedapi_client.api.discord_api import DiscordApi  # noqa: E501


class TestDiscordApi(unittest.TestCase):
    """DiscordApi unit test stubs."""

    def setUp(self) -> None:
        self.api = DiscordApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_fetch_discord_bio(self) -> None:
        """Test case for fetch_discord_bio.

        Fetch Discord Bio  # noqa: E501
        """

    def test_issue_clear_snipe(self) -> None:
        """Test case for issue_clear_snipe.

        Issue Clear Snipe  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
