# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel

class Card(BaseModel):
    """
    Card
    """
    small: Optional[Any] = None
    large: Optional[Any] = None
    wide: Optional[Any] = None
    id: Optional[Any] = None
    __properties = ["small", "large", "wide", "id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Card:
        """Create an instance of Card from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if small (nullable) is None
        # and __fields_set__ contains the field
        if self.small is None and "small" in self.__fields_set__:
            _dict['small'] = None

        # set to None if large (nullable) is None
        # and __fields_set__ contains the field
        if self.large is None and "large" in self.__fields_set__:
            _dict['large'] = None

        # set to None if wide (nullable) is None
        # and __fields_set__ contains the field
        if self.wide is None and "wide" in self.__fields_set__:
            _dict['wide'] = None

        # set to None if id (nullable) is None
        # and __fields_set__ contains the field
        if self.id is None and "id" in self.__fields_set__:
            _dict['id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Card:
        """Create an instance of Card from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Card.parse_obj(obj)

        _obj = Card.parse_obj({
            "small": obj.get("small"),
            "large": obj.get("large"),
            "wide": obj.get("wide"),
            "id": obj.get("id")
        })
        return _obj


