# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel

class GatewayUserStatus(BaseModel):
    """
    GatewayUserStatus
    """
    primary: Optional[Any] = None
    desktop: Optional[Any] = None
    mobile: Optional[Any] = None
    web: Optional[Any] = None
    __properties = ["primary", "desktop", "mobile", "web"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GatewayUserStatus:
        """Create an instance of GatewayUserStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if primary (nullable) is None
        # and __fields_set__ contains the field
        if self.primary is None and "primary" in self.__fields_set__:
            _dict['primary'] = None

        # set to None if desktop (nullable) is None
        # and __fields_set__ contains the field
        if self.desktop is None and "desktop" in self.__fields_set__:
            _dict['desktop'] = None

        # set to None if mobile (nullable) is None
        # and __fields_set__ contains the field
        if self.mobile is None and "mobile" in self.__fields_set__:
            _dict['mobile'] = None

        # set to None if web (nullable) is None
        # and __fields_set__ contains the field
        if self.web is None and "web" in self.__fields_set__:
            _dict['web'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GatewayUserStatus:
        """Create an instance of GatewayUserStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GatewayUserStatus.parse_obj(obj)

        _obj = GatewayUserStatus.parse_obj({
            "primary": obj.get("primary"),
            "desktop": obj.get("desktop"),
            "mobile": obj.get("mobile"),
            "web": obj.get("web")
        })
        return _obj


