# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel

class GuildMemberProfile(BaseModel):
    """
    GuildMemberProfile
    """
    guild_id: Optional[Any] = None
    bio: Optional[Any] = None
    banner: Optional[Any] = None
    accent_color: Optional[Any] = None
    __properties = ["guild_id", "bio", "banner", "accent_color"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GuildMemberProfile:
        """Create an instance of GuildMemberProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if guild_id (nullable) is None
        # and __fields_set__ contains the field
        if self.guild_id is None and "guild_id" in self.__fields_set__:
            _dict['guild_id'] = None

        # set to None if bio (nullable) is None
        # and __fields_set__ contains the field
        if self.bio is None and "bio" in self.__fields_set__:
            _dict['bio'] = None

        # set to None if banner (nullable) is None
        # and __fields_set__ contains the field
        if self.banner is None and "banner" in self.__fields_set__:
            _dict['banner'] = None

        # set to None if accent_color (nullable) is None
        # and __fields_set__ contains the field
        if self.accent_color is None and "accent_color" in self.__fields_set__:
            _dict['accent_color'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GuildMemberProfile:
        """Create an instance of GuildMemberProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GuildMemberProfile.parse_obj(obj)

        _obj = GuildMemberProfile.parse_obj({
            "guild_id": obj.get("guild_id"),
            "bio": obj.get("bio"),
            "banner": obj.get("banner"),
            "accent_color": obj.get("accent_color")
        })
        return _obj


