# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel

class InstagramCarouselMediaResponse(BaseModel):
    """
    InstagramCarouselMediaResponse
    """
    url: Optional[Any] = None
    preview_image_url: Optional[Any] = None
    preview_image_filename: Optional[Any] = None
    is_video: Optional[Any] = None
    filename: Optional[Any] = None
    __properties = ["url", "preview_image_url", "preview_image_filename", "is_video", "filename"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InstagramCarouselMediaResponse:
        """Create an instance of InstagramCarouselMediaResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if url (nullable) is None
        # and __fields_set__ contains the field
        if self.url is None and "url" in self.__fields_set__:
            _dict['url'] = None

        # set to None if preview_image_url (nullable) is None
        # and __fields_set__ contains the field
        if self.preview_image_url is None and "preview_image_url" in self.__fields_set__:
            _dict['preview_image_url'] = None

        # set to None if preview_image_filename (nullable) is None
        # and __fields_set__ contains the field
        if self.preview_image_filename is None and "preview_image_filename" in self.__fields_set__:
            _dict['preview_image_filename'] = None

        # set to None if is_video (nullable) is None
        # and __fields_set__ contains the field
        if self.is_video is None and "is_video" in self.__fields_set__:
            _dict['is_video'] = None

        # set to None if filename (nullable) is None
        # and __fields_set__ contains the field
        if self.filename is None and "filename" in self.__fields_set__:
            _dict['filename'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InstagramCarouselMediaResponse:
        """Create an instance of InstagramCarouselMediaResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InstagramCarouselMediaResponse.parse_obj(obj)

        _obj = InstagramCarouselMediaResponse.parse_obj({
            "url": obj.get("url"),
            "preview_image_url": obj.get("preview_image_url"),
            "preview_image_filename": obj.get("preview_image_filename"),
            "is_video": obj.get("is_video"),
            "filename": obj.get("filename")
        })
        return _obj


