# coding: utf-8

"""Melanie Data API.

A high performance & centrally cached API service for premium bots.

The version of the OpenAPI document:  commit 5b04d15 url_mime @ Aug 30 1:59 pm
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, Optional

from pydantic import BaseModel

from sharedapi_client.models.melanie_models_sharedapi_twitter_user_tweets_reason_description import MelanieModelsSharedapiTwitterUserTweetsReasonDescription


class MelanieModelsSharedapiTwitterUserTweetsReason(BaseModel):
    """MelanieModelsSharedapiTwitterUserTweetsReason."""

    description: Optional[MelanieModelsSharedapiTwitterUserTweetsReasonDescription] = None
    verified_since_msec: Optional[Any] = None
    __properties = ["description", "verified_since_msec"]

    class Config:
        """Pydantic configuration."""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias."""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias."""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MelanieModelsSharedapiTwitterUserTweetsReason:
        """Create an instance of MelanieModelsSharedapiTwitterUserTweetsReason from a JSON string."""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias."""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of description
        if self.description:
            _dict["description"] = self.description.to_dict()
        # set to None if verified_since_msec (nullable) is None
        # and __fields_set__ contains the field
        if self.verified_since_msec is None and "verified_since_msec" in self.__fields_set__:
            _dict["verified_since_msec"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MelanieModelsSharedapiTwitterUserTweetsReason:
        """Create an instance of MelanieModelsSharedapiTwitterUserTweetsReason from a dict."""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MelanieModelsSharedapiTwitterUserTweetsReason.parse_obj(obj)

        return MelanieModelsSharedapiTwitterUserTweetsReason.parse_obj(
            {
                "description": MelanieModelsSharedapiTwitterUserTweetsReasonDescription.from_dict(obj.get("description"))
                if obj.get("description") is not None
                else None,
                "verified_since_msec": obj.get("verified_since_msec"),
            },
        )
