# coding: utf-8

"""
    Melanie Data API 

    A high performance & centrally cached API service for premium bots. 

    The version of the OpenAPI document:  commit e9b768a rl @ Sep 3 3:07 pm
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel

class StoryItem(BaseModel):
    """
    StoryItem
    """
    id: Optional[Any] = None
    is_video: Optional[Any] = None
    filename: Optional[Any] = None
    url: Optional[Any] = None
    taken_at: Optional[Any] = None
    video_bytes: Optional[Any] = None
    __properties = ["id", "is_video", "filename", "url", "taken_at", "video_bytes"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StoryItem:
        """Create an instance of StoryItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if id (nullable) is None
        # and __fields_set__ contains the field
        if self.id is None and "id" in self.__fields_set__:
            _dict['id'] = None

        # set to None if is_video (nullable) is None
        # and __fields_set__ contains the field
        if self.is_video is None and "is_video" in self.__fields_set__:
            _dict['is_video'] = None

        # set to None if filename (nullable) is None
        # and __fields_set__ contains the field
        if self.filename is None and "filename" in self.__fields_set__:
            _dict['filename'] = None

        # set to None if url (nullable) is None
        # and __fields_set__ contains the field
        if self.url is None and "url" in self.__fields_set__:
            _dict['url'] = None

        # set to None if taken_at (nullable) is None
        # and __fields_set__ contains the field
        if self.taken_at is None and "taken_at" in self.__fields_set__:
            _dict['taken_at'] = None

        # set to None if video_bytes (nullable) is None
        # and __fields_set__ contains the field
        if self.video_bytes is None and "video_bytes" in self.__fields_set__:
            _dict['video_bytes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StoryItem:
        """Create an instance of StoryItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StoryItem.parse_obj(obj)

        _obj = StoryItem.parse_obj({
            "id": obj.get("id"),
            "is_video": obj.get("is_video"),
            "filename": obj.get("filename"),
            "url": obj.get("url"),
            "taken_at": obj.get("taken_at"),
            "video_bytes": obj.get("video_bytes")
        })
        return _obj


